### ISSUE TITLE
Modal doesn't display on reopen

### ISSUE THREAD

**Issue by furzeface** [furzeface/blackledge#2]
AndyMcInnes created an issue 2015-09-17
_When you reopen the modal a second time it doesn't display. Like the animation though :)_

**Comment by grumpydev22** [comment]
Fixed in PR, the init was being called after the modal had opened which caused the click event to be duplicated, words, words, words, fixed, fixed, fixed. Also noticed that the modal was closing when the content was clicked, fixed this too

**Comment by furzeface** [comment]
Thanks Grumpy @ablackledge! :heart_eyes_cat:
