### ISSUE TITLE
Other carousel options

### ISSUE THREAD

**Issue by antoniojl** [furzeface/blackledge#22]
The carousel in this library doesn't pass through data-autoplay or data-loop attributes to the owlcarousel options object. Can you fix this please? I'm trying to use this on a very important project today.

**Comment by antoniojl** [comment]
Is this fixed yet.

**Comment by antoniojl** [comment]
Hello.

**Comment by antoniojl** [comment]
Ed Balls

**Comment by ablackledge** [comment]
I CAN'T BELIEVE THIS ISN'T FIXED YET!

**Comment by furzeface** [comment]
IT WORKS ON MY MACHINE
