### ISSUE TITLE
Modularise the heck out of everything.

### ISSUE THREAD

**Issue by furzeface** [furzeface/blackledge#24]
I want to move everything related to each component into subdirectories so the data, HTML, CSS and JavaScript are all contained together. That way the components can be taken out and installed to a project far more easily.

Also change the build tasks and _order.less file to reflect this (do as part of this feature).

Also update the documentation per example page to reflect this (create a seperate issue).

Eg:
components/
--- data/component.json
--- scripts/component.js
--- styles/component.{less,scss}
--- component.hbs

**Comment by ablackledge** [comment]
http://cdn.meme.am/instances/60505565.jpg

**Comment by furzeface** [comment]
Done @ablackledge! Makes way more sense I reckon eg: https://github.com/furzeface/blackledge/tree/master/src/components/alerts

:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :sunglasses: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: 
:octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat: :octocat:
