### ISSUE TITLE
Move to Sass

### ISSUE THREAD

**Issue by furzeface** [furzeface/blackledge#8]
Because [Sass](http://sass-lang.com).

**Comment by furzeface** [comment]
Note: @ablackledge has started this [here](https://github.com/grumpydev22/andyblackledge/tree/master/src/assets/styles/sass)

**Comment by ablackledge** [comment]
:smile:

**Comment by furzeface** [comment]
*Done!* Big thanks to @ablackledge, copied a few bits from his repo :smile: 

Just need to fix a build issue with bower now and should be god to merge :octocat:
